"""removing grocery and grocery item tables

Revision ID: 66c88cc0b5d5
Revises: 4c87c582348d
Create Date: 2023-09-08 16:25:55.013431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c88cc0b5d5'
down_revision = '4c87c582348d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grocery_items')
    op.drop_table('grocery_lists')
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_days_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_days_list_id_lists'), 'lists', ['list_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_days_event_id_events'), 'events', ['event_id'], ['id'])
        batch_op.drop_column('id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('date')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_day_id_days', type_='foreignkey')
        batch_op.drop_column('day_id')

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lists_day_id_days', type_='foreignkey')
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_lists_day_id_days', 'days', ['day_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_events_day_id_days', 'days', ['day_id'], ['id'])

    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_days_event_id_events'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_days_list_id_lists'), type_='foreignkey')
        batch_op.create_foreign_key('fk_days_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('list_id')
        batch_op.drop_column('event_id')

    op.create_table('grocery_lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('day_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], name='fk_grocery_lists_day_id_days'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_grocery_lists_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grocery_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('grocery_list_id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], name='fk_grocery_items_grocery_list_id_grocery_lists', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
