"""added user foreign key to days table

Revision ID: 74676735556e
Revises: d923585f4068
Create Date: 2023-09-06 13:41:13.738031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74676735556e'
down_revision = 'd923585f4068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_days_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_days_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
