"""dropping date field in event model

Revision ID: efdf2819bd5a
Revises: 71dc6c77c2cb
Create Date: 2023-09-30 16:24:03.488139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdf2819bd5a'
down_revision = '71dc6c77c2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
